[package]
name = "derrik"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
log = "0.4.22"
once_cell = "1.19.0"
